import argparse
import os
from datetime import datetime
from PIL import Image
 
from model_ResNet50 import load_model, load_labels, preprocess_image, predict
from gradcam import generate_gradcam, overlay_heatmap_on_image
from perturbations import add_gaussian_noise
from perturbations import add_rotation
from perturbations import add_occlusion
 

 # MAIN.PY IS OUTDATED AND WAS USED AS A TERMINAL BASED WAY TO TEST THE VERY BASIC VERSION OF THE PROJECT.


 # PLEASE RUN THE STREAMLIT APP INSTEAD FOR FULL FUNCTIONALITY. SEE APP.PY



 





# HOW TO RUN (NOTE: OUTDATED!!! RUN APP.PY INSTEAD)
#
#   1. Open your terminal and navigate to your project folder
#
#   2. Basic run (no perturbation):
#        python main.py --image examples/test.jpg                      (image you want to test)
#
#   3. How to run with perturbation(s): We currently support three perturbations: noise, rotation, and occlusions
#        python main.py --image examples/test.jpg --noise              (adds Gaussian noise to the image)
#        python main.py --image examples/test.jpg --rotation           (adds a counterclockwise rotation to the image)
#        python main.py --image examples/test.jpg --occlusion          (adds an occluded black rectangle in the image)
#
#   4. The following perturbation options are available as arguments to modify the strength of the perturbations:
#        --noise_strength    intensity of the Gaussian noise (default: 25, range: 5-100)
#        --rotation_angle    degrees to rotate counter-clockwise (default: 30)
#        --occlusion_size    width and height of the black rectangle in pixels (default: 64)
#        --occlusion_x       left edge of rectangle in pixels from left edge of the image (default: auto centered)
#        --occlusion_y       top edge of rectangle in pixels from top edge of the image (default: auto centered)
#
#   5. Perturbations can be stacked in any combination as arguments. see examples below:
#        python main.py --image examples/test.jpg --noise --rotation --rotation_angle 45
#        python main.py --image examples/test.jpg --noise --noise_strength 60 --rotation --occlusion --occlusion_size 50 --occlusion_x 30
#
#       In such cases, all requested perturbations with request strength levels are applied to the image one after another in the order Gaussian noise, rotation, occlusion
#
#   6. Optional: you can also add an argument specify how many predictions to show (default is 5):
#        python main.py --image examples/test.jpg --noise --top_k 3
#
#   7. For help:
#        python main.py -h
#
#   OUTPUT (no perturbation):
#       See top_k predictions generated by the model in terminal
#       Heatmap saved to outputs/
#       File naming is generated such as: outputs/filename_gradcam_result_2026-04-24_11:19:52.jpg
#
#   OUTPUT (with perturbation):
#       See top_k predictions generated by the model for both when no perturbations are applied, and for when all requested perturbations are applied
#       Side-by-side heatmap comparison saved to outputs_perturbations/
#       LEFT PANEL OF THE OUTPUT  = original image heatmap
#       RIGHT PANEL OF THE OUTPUT  = perturbed image heatmap
#       NOTE: Output file naming is based on the image file name, all perturbations applied and all added strengths, and date and time of run for easy record.
#           EXAMPLE: outputs_perturbations/filename_gaussian25_rotation30_occlusion50x60ycenter_comparison_2026-04-24_11:19:52.jpg





# ArgumentParser is likely the best way for the user to enter the path to the input image, definitely
# way better than using a basic input scanner, especially due to the help menu that guides the user
# to better test the basic functionality of the Grad-CAM.

def parse_args():
    parser = argparse.ArgumentParser(
        description="Basic version of CNN Visualizer. Upload path to the input image, see top 5 model predictions, then see the visual Grad-CAM heatmap output for that image, with optional perturbation comparison (for now, Gaussian Noise)"
    )
    parser.add_argument(
        "--image",
        type=str,
        required=True,
        help="Path to the input image (e.g. examples/dog.jpg)"
    )
    # decided to also add an argument K for the top K amount of predictions the user wants to display. Default is 5 
    parser.add_argument(
        "--top_k",
        type=int,
        default=5,
        help="How many predictions would you like to display? (Default is 5)"
    )

    # Argument to add Gaussian Noise to the image:
    parser.add_argument(
        "--noise",
        action="store_true",
        help="Apply Gaussian Noise to your selected image, and generate a side-by-side comparison heatmap"
    )

    # The following manipulates the strength of the Gaussian Noise. For more information, see perturbations.py 
    parser.add_argument(
        "--noise_strength",
        type=int,
        default=25,
        help="Strength of noise (default: 25, range: 5-100)"
    )

    # Argument to add a rotation to the image:

    parser.add_argument(
        "--rotation",
        action="store_true",
        help="Rotate your selected image, and generate a side-by-side comparison heatmap"
    )

    # Argument to specify the degrees to rotate the image counter-clockwise. The default rotation is 30 degrees if not otherwise specified.
    parser.add_argument(
        "--rotation_angle",
        type=int,
        default=30,
        help="Degrees to rotate the selected image counter-clockwise"
    )

    # Argument to add a black rectangle to the selected image
    parser.add_argument(
        "--occlusion",
        action="store_true",
        help="Apply an occlusion (in the form of a black rectangle) to your selected image"
    )

    # Argument to set the size of the occlusion (black rectangle) in pixels. The default is 64 pixels width and height

    parser.add_argument(
        "--occlusion_size",
        type=int,
        default=64,
        help="Size of the occlusion box in pixels. Default is 64 pixels."
    )

    # With the occlusion_x argument, you can set the distance (in pixels) of the left edge of the occlusion rectangle from the left edge of the specified image. If not specified, the occlusion
    # rectangle will by default by centered. See add_occlusion in perturbations.py for more information
    parser.add_argument(
        "--occlusion_x",
        type=int,
        default=None,
        help="Left edge of occlusion box in pixels from the left edge of the image. Default is auto-centered"
    )

    # With the occlusion_y argument, you can set the distance (in pixels) of the top edge of the occlusion rectangle from the top edge of the specified image. If not specified, the occlusion
    # rectangle will by default by centered. See add_occlusion in perturbations.py for more information
    parser.add_argument(
        "--occlusion_y",
        type=int,
        default=None,
        help="Top edge of occlusion box in pixels from the top edge of the image. Default is auto-centered"
    )



    

    return parser.parse_args()
 
 
def make_output_filename(image_path, output_dir, suffix="gradcam_result"): # suffix parameter is different when noise is applied
    # NOTE: See the build_suffix method
    # code for custom output path
    # Build a standard output filename like examples/dog.jpg -> outputs/dog_gradcam_result_2026-04-24_11:19:52.jpg
    # Modified due to the addition of perturbations. NOTE: See build_suffix method
    
    base_name = os.path.basename(image_path)
    base_of_imagepath = os.path.splitext(base_name)[0] # if basename is dog.jpg, baseofimagepath will be "dog"
    
    # I decided to use Python's datetime module, which gives the current date and time of testing
    # trying to format the current date and time into the output filename as well

    time_of_testing = datetime.now()
    timestamp = time_of_testing.strftime("%Y-%m-%d_%H:%M:%S")

    output_filename = os.path.join(output_dir, f"{base_of_imagepath}_{suffix}_{timestamp}.jpg")
    return output_filename 

 
def print_predictions(predictions):
    print("\nTop Predictions by ResNet50 Model:")
    for rank, (class_name, confidence) in enumerate(predictions, start=1):
        print(f"  {rank}. {class_name:<30} {confidence:.2f}%")

# The following method, create_side_by_side_heatmaps, creates side by side heatmaps when a perturbation is applied. 
#       LEFT PANEL  = original image heatmap (provided image with no noise applied)
#       RIGHT PANEL = noisy image heatmap (provided image with the requested noise applied)
def create_side_by_side_heatmaps(left_image, right_image, divider_width = 4):
    # left_image and right_image are the respective PIL heatmap images. 
    # divider_width is the width of the vertical divider (in pixels) between the images. Change this width to your desire.

    # This method returns a single PIL Image with left and right panels joined horizontally.
    total_heatmap_width = left_image.width + divider_width + right_image.width
    total_heatmap_height = max(left_image.height, right_image.height)
    combined = Image.new("RGB", (total_heatmap_width, total_heatmap_height), color=(200, 200, 200))
    combined.paste(left_image, (0, 0))
    combined.paste(right_image, (left_image.width + divider_width, 0))
 
    return combined

def run_no_noise(args, model, labels):

    # everything below this point is very similar to the testing code in model_ResNet50.py and gradcam.py

    os.makedirs("outputs", exist_ok=True) # in case the output folder doesn't exist
    image_tensor = preprocess_image(args.image)
    predictions = predict(model, image_tensor, labels, top_k=args.top_k)
    print_predictions(predictions)
 
    heatmap = generate_gradcam(model, image_tensor)
    original_image = Image.open(args.image).convert("RGB")
    overlaid = overlay_heatmap_on_image(original_image, heatmap)
 
    
    output_path = make_output_filename(args.image, "outputs")
    Image.fromarray(overlaid).save(output_path)
    print(f"Congrats, your heatmap has successfully been saved to: {output_path} Check it out in the outputs folder, and stay tuned for what is to come with this project!\n")

def build_perturbed_image(image, args):
    # Apply all requested perturbations/arguments in sequence to the specified image.
    # Returns a PIL image with all perturbations applied

    perturbed_image = image
    if args.noise:
        perturbed_image = add_gaussian_noise(perturbed_image, strength = args.noise_strength)
    if args.rotation:
        perturbed_image = add_rotation(perturbed_image, angle = args.rotation_angle)
    if args.occlusion:
        perturbed_image = add_occlusion(perturbed_image, width = args.occlusion_size, height = args.occlusion_size, x = args.occlusion_x, y = args.occlusion_y)
    return perturbed_image

# Build the output filename suffix reflecting all perturbations applied
# An example of such a filename suffix is gaussian25_rotation30_occlusion64x=50y=50_comparison
def build_suffix(args):
    # parts is an array of all different noise arguments to add 
    parts = []
    if args.noise:
        parts.append(f"gaussian{args.noise_strength}")
    if args.rotation:
        parts.append(f"rotation{args.rotation_angle}")
    if args.occlusion:
        x_str = str(args.occlusion_x) if args.occlusion_x is not None else "center"
        y_str = str(args.occlusion_y) if args.occlusion_y is not None else "center"
        parts.append(f"occlusion{args.occlusion_size}x{x_str}y{y_str}")
    parts.append("comparison")
    return "_".join(parts)


def run_with_perturbations(args, model, labels):

    os.makedirs("outputs_perturbations", exist_ok=True)
    original_image = Image.open(args.image).convert("RGB")
    # making the perturbed image
    perturbed_image = build_perturbed_image(original_image, args)
    

    print("\n ------ ORIGINAL IMAGE PREDICTIONS (NO NOISE APPLIED) ---------------------")
    original_tensor = preprocess_image(args.image)
    original_predictions = predict(model, original_tensor, labels, top_k=args.top_k)
    print_predictions(original_predictions)

    original_heatmap = generate_gradcam(model, original_tensor)
    original_heatmap_overlaid = overlay_heatmap_on_image(original_image, original_heatmap)

    print("\n ------ PREDICTIONS WITH ALL PERTURBATIONS APPLIED = {} ---------------------".format(build_suffix(args)))
    perturbed_tensor = preprocess_image(perturbed_image)
    perturbed_predictions = predict(model, perturbed_tensor, labels, top_k=args.top_k)
    print_predictions(perturbed_predictions)
    perturbed_heatmap = generate_gradcam(model, perturbed_tensor)
    perturbed_heatmap_overlaid = overlay_heatmap_on_image(perturbed_image, perturbed_heatmap)

    # call method create_side_by_side_heatmaps
    left  = Image.fromarray(original_heatmap_overlaid)
    right = Image.fromarray(perturbed_heatmap_overlaid)
    side_by_side = create_side_by_side_heatmaps(left, right)

    # Creating the output path for noise
    output_path = make_output_filename(args.image, "outputs_perturbations", suffix=build_suffix(args))

    side_by_side.save(output_path) 

    print(f"Congrats, your side-by-side heatmaps have successfully been saved to: {output_path} Check it out in the outputs folder, and stay tuned for what is to come with this project!\n")
    
def main():
    args = parse_args()
 
    if not os.path.exists(args.image):
        print(f"We couldn't find an image at '{args.image}', please try again with a correct image")
        return
 
    print(f"\nImage: {args.image}")
    model = load_model()
    labels = load_labels()
 
    if args.noise or args.rotation or args.occlusion:
        run_with_perturbations(args, model, labels)
    else:
        run_no_noise(args, model, labels)


 
if __name__ == "__main__":
    main()